version: '3.8'

services:
  db:
    image: postgres:15
    container_name: finless_db
    restart: always
    environment:
      POSTGRES_DB: finless_db
      POSTGRES_USER: finless_user
      POSTGRES_PASSWORD: finless_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
