# Generated by Django 5.1.1 on 2026-09-25 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('risk_level', models.CharField(max_length=20)),
                ('profitability', models.DecimalField(decimal_places=2, max_digits=5)),
                ('liquidity_deadline', models.IntegerField(help_text='Prazo em dias')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
