# Generated by Django 5.1.1 on 2026-09-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='ticker',
            field=models.CharField(blank=True, help_text='Ticker B3 (ex: PETR4.SA, MXRF11.SA)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='profitability',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rentabilidade fixa se não houver ticker', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='type',
            field=models.CharField(help_text='FIXED_INCOME, STOCK, FII, etc', max_length=50),
        ),
    ]
